name: github_webview
description: to show krumaska github blog using webview.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  fluttertoast: ^4.0.1
  flutter_webview_plugin: ^0.3.11

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true